; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board = rpipico2
lib_deps = 
	adafruit/Adafruit INA260 Library@^1.5.2
	adafruit/Adafruit ICM20X@^2.0.7
	sparkfun/SparkFun Indoor Air Quality Sensor - ENS160@^1.1.0
	sparkfun/SparkFun AS7331 Arduino Library@^2.1.1
	adafruit/RTClib@^2.1.4
	sparkfun/SparkFun High Precision Temperature Sensor TMP117 Qwiic@^1.2.5
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit SHTC3 Library@^1.0.1
	adafruit/Adafruit BME680 Library@^2.0.5
	https://github.com/DFRobot/DFRobot_OzoneSensor.git#V1.0.1
	snaildragon/MightyOhmGeigerCounter@^1.2.0
